export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const AJAX_CALL_START = 'AJAX_CALL_START';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
